# Generated by Django 3.1.1 on 2020-12-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentcare', '0049_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='Week_Number',
            field=models.IntegerField(),
        ),
    ]
