# Generated by Django 3.1.1 on 2020-12-12 21:57

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('mentcare', '0047_auto_20201212_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='MW'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_of_guardian',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='MW'),
        ),
    ]
