# Generated by Django 3.1.1 on 2020-12-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentcare', '0048_auto_20201212_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Week_Number', models.IntegerField(max_length=20)),
                ('Employee_Name', models.TextField(max_length=1000)),
                ('Ward_Name', models.TextField(max_length=1000)),
                ('Shift', models.TextField(max_length=1000)),
            ],
        ),
    ]
