# Generated by Django 3.1.1 on 2020-12-12 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentcare', '0050_auto_20201212_1446'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schedule',
            new_name='Schedules',
        ),
    ]
