# Generated by Django 3.1.1 on 2020-12-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentcare', '0051_auto_20201212_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hivtest',
            name='if_on_HAART_when_initiated',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='medicalpsychiatrichistorys',
            name='last_time_treated_at',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
